# Generated by Django 4.2.5 on 2023-10-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='bookreport',
            name='brokens',
        ),
        migrations.RemoveField(
            model_name='bookreport',
            name='losts',
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='message',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bookreport',
            name='brokens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bookreport',
            name='losts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
