# Generated by Django 4.2.6 on 2023-10-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_remove_roomreport_cancel_alter_bookreport_brokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='brokens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='losts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
