# Generated by Django 4.2.6 on 2023-10-29 05:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0004_alter_bookreport_brokens_alter_bookreport_losts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookReport',
            new_name='Report',
        ),
    ]
