# Generated by Django 4.2.6 on 2023-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0006_alter_report_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(max_length=12),
        ),
    ]
