# Generated by Django 4.2.6 on 2023-10-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0007_alter_report_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomReport',
        ),
    ]
