# Generated by Django 4.2.6 on 2023-10-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_merge_0002_auto_20231024_1303_0004_auto_20231027_0201'),
        ('ulasan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
