# Generated by Django 4.2.6 on 2023-10-27 04:21

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "data_buku.json")

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231024_1303'),
        ('book', '0004_auto_20231027_0201'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
