# Generated by Django 4.2.6 on 2023-10-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistem_manajemen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruangan',
            old_name='ketersidiaan',
            new_name='ketersediaan',
        ),
    ]
